# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'rails', '4.0.5'

# Sqlite3 & rspec
group :development, :test do
  gem 'sqlite3', '1.3.8'
  gem 'rspec-rails', '2.13.1'
end

# FIX
gem 'rb-readline'
